name: CMakeFullTest

on:
  push:
    tags:
      - v**

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  ubuntu_test:
    name: Ubuntu tests

    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler:
          - { name: GCC, cc: gcc-10, cxx: g++-10 }
          - { name: Clang, cc: clang-10, cxx: clang++-10 }
        flags: [98, 11, 14, 17]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      env:
        CC: ${{ matrix.compiler.cc }}
        CXX: ${{ matrix.compiler.cxx }}

      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/build
      env:
        CC: ${{ matrix.compiler.cc }}
        CXX: ${{ matrix.compiler.cxx }}
      # Note the current convention is to use the -S and -B options here to specify source
      # and build directories, but this is only available with CMake 3.13 and higher.
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_CXX_STANDARD=${{ matrix.flags }} -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DNANO_TEST_BUILD_EXAMPLES=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      env:
        CC: ${{ matrix.compiler.cc }}
        CXX: ${{ matrix.compiler.cxx }}
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ./examples/assert/nano-test-assert; ./examples/basic/nano-test-basic; ./examples/range/nano-test-range

  macos_test:

    name: MacOS tests
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    # runs-on: macos-10.15

    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]
        flags: [98, 11, 14, 17]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment

      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/build

      # Note the current convention is to use the -S and -B options here to specify source
      # and build directories, but this is only available with CMake 3.13 and higher.
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_CXX_STANDARD=${{ matrix.flags }} -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DNANO_TEST_BUILD_EXAMPLES=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash

      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash

      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ./examples/assert/nano-test-assert; ./examples/basic/nano-test-basic; ./examples/range/nano-test-range

  windows_test:
    name: Windows tests

    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-2019

    strategy:
      matrix:
        flags: [98, 11, 14, 17]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment

      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake

      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      working-directory: ${{github.workspace}}/build

      # Note the current convention is to use the -S and -B options here to specify source
      # and build directories, but this is only available with CMake 3.13 and higher.
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake ${{github.workspace}} -DCMAKE_CXX_STANDARD=${{ matrix.flags }} -DCMAKE_BUILD_TYPE=Release -DNANO_TEST_BUILD_EXAMPLES=ON

    - name: Build
      working-directory: ${{github.workspace}}/build

      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config Release

    - name: Test
      working-directory: ${{github.workspace}}/build

      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ./examples/assert/Release/nano-test-assert.exe; ./examples/basic/Release/nano-test-basic.exe; ./examples/range/Release/nano-test-range.exe
